name: qbox_mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  socket_io_client: ^1.0.2
  flutter_svg: ^2.0.10+1
  assets_audio_player: ^3.1.1

  # for android & ios
  flutter_webrtc: ^0.6.4

  # for ios
  # flutter_webrtc: ^0.11.6

  voice_message_package: ^2.2.1

  file_picker: ^8.0.6
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.1+2
  video_player: ^2.9.1
  flick_video_player: ^0.9.0

  badges: ^3.1.2
  # webview_flutter: ^4.9.0
  html_viewer_elite: ^0.0.4
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
